// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documents_parser.actions;

import java.io.IOException;
import java.io.InputStream;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
import org.apache.poi.hssf.usermodel.*;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_Parse_Excel extends UserAction<java.lang.String>
{
	/** @deprecated use ParamDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ParamDoc;
	private final system.proxies.FileDocument ParamDoc;

	public JA_Parse_Excel(
		IContext context,
		IMendixObject _paramDoc
	)
	{
		super(context);
		this.__ParamDoc = _paramDoc;
		this.ParamDoc = _paramDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), _paramDoc);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        StringBuilder content = new StringBuilder();

        try {
            InputStream excelStream = Core.getFileDocumentContent(getContext(), this.ParamDoc.getMendixObject());
            String fileName = this.ParamDoc.getName();

            Workbook workbook;
            if (fileName.endsWith(".xls")) {
                workbook = new HSSFWorkbook(excelStream); // .xls format
            } else if (fileName.endsWith(".xlsx")) {
                workbook = new XSSFWorkbook(excelStream); // .xlsx format
            }
          else if (fileName.endsWith(".xlsm")) {
            workbook = new XSSFWorkbook(excelStream);} else {
                throw new RuntimeException("Unsupported Excel file format");
            }

            for (int sheetIndex = 0; sheetIndex < workbook.getNumberOfSheets(); sheetIndex++) {
                Sheet sheet = workbook.getSheetAt(sheetIndex);
                for (Row row : sheet) {
                    for (Cell cell : row) {
                        if (cell.getCellType() == CellType.STRING) {
                            String text = cell.getStringCellValue();
                            content.append(text).append("\t");
                        }
                    }
                    content.append("\n");
                }
            }

            workbook.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return content.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Parse_Excel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
