// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documents_parser.actions;

import java.io.IOException;
import java.io.InputStream;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_Parse_PDF extends UserAction<java.lang.String>
{
	/** @deprecated use ParamDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ParamDoc;
	private final system.proxies.FileDocument ParamDoc;

	public JA_Parse_PDF(
		IContext context,
		IMendixObject _paramDoc
	)
	{
		super(context);
		this.__ParamDoc = _paramDoc;
		this.ParamDoc = _paramDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), _paramDoc);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        StringBuilder content = new StringBuilder();

        try {
            InputStream pdfStream = Core.getFileDocumentContent(getContext(), this.ParamDoc.getMendixObject());
            PDDocument document = PDDocument.load(pdfStream);
            PDFTextStripper stripper = new PDFTextStripper();

            for (int pageNum = 1; pageNum <= document.getNumberOfPages(); pageNum++) {
                stripper.setStartPage(pageNum);
                stripper.setEndPage(pageNum);
                String text = stripper.getText(document);
                content.append("Page ").append(pageNum).append(":\n").append(text).append("\n");
            }

            document.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return content.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Parse_PDF";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
